# Configuración del sitio

# Importar el tema
theme: jekyll-theme-chirpy

# Idioma del sitio web › http://www.lingoes.net/en/translator/langcode.htm
# Si coincide con el nombre de uno de los archivos en la carpeta `_data/locales`,
# el idioma del diseño también se cambiará. De lo contrario, se usará el valor por defecto 'en'.
lang: es

# Cambia a tu zona horaria › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Lima

# Configuración de jekyll-seo-tag › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Drowsy Researcher # título principal

tagline: Bitácora de un estudiante de ciberseguridad y entusiasta autodidacta # se mostrará como subtítulo

description: >- # usado para metadatos SEO y el feed Atom
  Blog de Carlos Lopez, estudiante de Administración de Ciberseguridad y entusiasta autodidacta de la ciberseguridad. Comparte conocimientos, investigaciones y experiencias técnicas en laboratorios, enfocados en seguridad informática, ciencia y aprendizaje continuo.

# Rellena con el protocolo y nombre de dominio de tu sitio.
# Ejemplo: 'https://usuario.github.io', sin la barra al final.
url: "https://carloslopez-ciber.github.io"

github:
  username: CarlosLopez-Ciber # cambia esto por tu nombre de usuario en GitHub

# twitter:
#  username: twitter_username # cambia esto por tu nombre de usuario en Twitter

social:
  # Cambia esto por tu nombre completo.
  # Se mostrará como autor por defecto y propietario de los derechos en el pie de página
  name: Carlos Lopez
  #email: example@domain.com # cambia esto por tu correo electrónico
  links:
    # El primer enlace sirve como enlace de derechos de autor
    # https://twitter.com/username # cambia esto por tu Twitter
    - https://github.com/CarlosLopez-Ciber # cambia esto por tu GitHub
    # Descomenta las siguientes líneas para agregar más redes sociales
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Configuración de verificación del sitio
webmaster_verifications:
  google: # ingresa tu código de verificación de Google
  bing: # ingresa tu código de verificación de Bing
  alexa: # ingresa tu código de verificación de Alexa
  yandex: # ingresa tu código de verificación de Yandex
  baidu: # ingresa tu código de verificación de Baidu
  facebook: # ingresa tu código de verificación de Facebook

# ↑ --------------------------
# Fin de la configuración de `jekyll-seo-tag`

# Configuración de análisis web
analytics:
  google:
    id: # ingresa tu ID de Google Analytics
  goatcounter:
    id: # ingresa tu ID de GoatCounter
  umami:
    id: # ingresa tu ID de Umami
    domain: # ingresa tu dominio de Umami
  matomo:
    id: # ingresa tu ID de Matomo
    domain: # ingresa tu dominio de Matomo
  cloudflare:
    id: # ingresa tu token de Cloudflare Web Analytics
  fathom:
    id: # ingresa tu ID del sitio en Fathom

# Configuración de conteo de vistas
pageviews:
  provider: # actualmente solo se admite 'goatcounter'

# Preferencia del esquema de color.
#
# Nota: Si se deja vacío, se seguirá por defecto el esquema de color del sistema,
# y habrá un interruptor para cambiar entre el tema claro y oscuro
# en la parte inferior izquierda de la barra lateral.
#
# Opciones disponibles:
#
#     light — Usar el esquema de color claro
#     dark — Usar el esquema de color oscuro
#
theme_mode: # [light | dark]

# El endpoint del CDN para recursos multimedia.
# Ten en cuenta que una vez asignado, la URL del CDN
# se agregará a todos los recursos multimedia (avatar del sitio, imágenes de publicaciones, archivos de audio y video)
# cuyos caminos comiencen con '/'
#
# Ejemplo: 'https://cdn.com'
cdn:

# Avatar en la barra lateral, admite recursos locales o de CORS
avatar: _site/assets/img/favicons/web-app-manifest-192x192.png

# URL de la imagen de vista previa social del sitio, usada en la metaetiqueta SEO `og:image`.
# Puede ser sobrescrita por una imagen personalizada `page.image` en los metadatos de una página.
social_preview_image: # cadena de texto, recurso local o CORS

# Tipo booleano, interruptor global para mostrar la tabla de contenido (TOC) en publicaciones.
toc: true

comments:
  # Interruptor global para el sistema de comentarios en las publicaciones. Si se deja vacío, estará desactivado.
  provider: # [disqus | utterances | giscus]
  # Las opciones de proveedor son las siguientes:
  disqus:
    shortname: # completa con el shortname de Disqus › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # Configuración de utterances › https://utteranc.es/
  utterances:
    repo: # <usuario-github>/<repositorio>
    issue_term: # < url | pathname | title | ...>
  # Opciones de Giscus › https://giscus.app
  giscus:
    repo: # <usuario-github>/<repositorio>
    repo_id:
    category:
    category_id:
    mapping: # opcional, por defecto es 'pathname'
    strict: # opcional, por defecto es '0'
    input_position: # opcional, por defecto es 'bottom'
    lang: # opcional, por defecto usa el valor de `site.lang`
    reactions_enabled: # opcional, por defecto es '1'

# Recursos estáticos autohospedados, opcional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # booleano, si se deja vacío será false
    # especificar el entorno Jekyll, vacío significa ambos
    # solo funciona si `assets.self_host.enabled` es 'true'
    env: # [development | production]

pwa:
  enabled: true # Habilita la característica PWA (instalable)
  cache:
    enabled: true # Habilita la caché offline para PWA
    # Las rutas definidas aquí serán excluidas de la caché PWA.
    # Usualmente se usa cuando otro sitio web comparte el mismo dominio.
    deny_paths:
      # - "/ejemplo"  # Las URLs que coincidan con `<SITE_URL>/ejemplo/*` no serán almacenadas en caché por PWA

paginate: 10

# La URL base de tu sitio
baseurl: ""

# ------------ Las siguientes opciones no se recomienda modificarlas ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Opciones de Rouge › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # Una cadena vacía significa todos los archivos del proyecto
      type: posts
    values:
      layout: post
      comments: true # Habilitar comentarios en publicaciones
      toc: true # Mostrar tabla de contenido en publicaciones
      # NO modifiques el siguiente parámetro a menos que sepas actualizar todos los enlaces de publicaciones
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # ver `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - rollup.config.js
  - "package*.json"

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
