# Configuración del Sitio

# Importar el tema
theme: jekyll-theme-chirpy

# El idioma de la página web › http://www.lingoes.net/en/translator/langcode.htm
# Si coincide con el nombre de uno de los archivos en la carpeta `_data/locales`, también cambiará el idioma del diseño,
# de lo contrario, el idioma del diseño usará el valor predeterminado 'en'.
lang: es

# Cambia a tu zona horaria › https://kevinnovak.github.io/Time-Zone-Picker
timezone: America/Lima

# Configuración de jekyll-seo-tag › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Carlos Lopez # el título principal

tagline: Un tema Jekyll enfocado en el texto # se mostrará como subtítulo

description: Blog de ciberseguridad con recursos, técnicas y consejos ideal para quienes buscan aprender y mejorar su seguridad digital.

# Completa el protocolo y el nombre de host para tu sitio.
# Ej. 'https://nombredeusuario.github.io', nota que no termina con '/'.
url: "https://carloslopez-ciber.github.io/"

github:
  username: CarlosLopez-Ciber # cambia a tu nombre de usuario de GitHub

twitter:
  username: twitter_username # cambia a tu nombre de usuario de Twitter

social:
  # Cambia a tu nombre completo.
  # Se mostrará como el autor predeterminado de las publicaciones y el propietario de los derechos de autor en el pie de página
  name: Carlos Lopez
  email: example@domain.com # cambia a tu dirección de correo electrónico
  links:
    # El primer elemento sirve como enlace del propietario de los derechos de autor
    - https://twitter.com/username # cambia a tu página de inicio de Twitter
    - https://github.com/username # cambia a tu página de inicio de GitHub
    # Descomenta abajo para agregar más enlaces sociales
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Configuración de Verificación del Sitio
webmaster_verifications:
  google: # completa con tu código de verificación de Google
  bing: # completa con tu código de verificación de Bing
  alexa: # completa con tu código de verificación de Alexa
  yandex: # completa con tu código de verificación de Yandex
  baidu: # completa con tu código de verificación de Baidu
  facebook: # completa con tu código de verificación de Facebook

# ↑ --------------------------
# Fin de la configuración de `jekyll-seo-tag`

# Configuración de Analítica Web
analytics:
  google:
    id: # completa con tu ID de Google Analytics
  goatcounter:
    id: # completa con tu ID de GoatCounter
  umami:
    id: # completa con tu ID de Umami
    domain: # completa con tu dominio de Umami
  matomo:
    id: # completa con tu ID de Matomo
    domain: # completa con tu dominio de Matomo
  cloudflare:
    id: # completa con tu token de Cloudflare Web Analytics
  fathom:
    id: # completa con tu ID de Sitio de Fathom

# Configuración de vistas de página
pageviews:
  provider: # solo admite 'goatcounter' actualmente

# Configuración de preferencia de esquema de color.
#
# Nota: Mantener vacío seguirá el esquema de color del sistema por defecto,
# y habrá un botón para cambiar el tema entre oscuro y claro
# en la esquina inferior izquierda de la barra lateral.
#
# Opciones disponibles:
#
#     light — Usar el esquema de color claro
#     dark — Usar el esquema de color oscuro
#
theme_mode: # [light | dark]

# Punto final CDN para recursos multimedia.
# Nota que una vez asignado, la url del CDN
# se agregará a todos los recursos multimedia (avatar del sitio, imágenes de publicaciones, archivos de audio y video) que comiencen con '/'
#
# ej. 'https://cdn.com'
cdn:

# el avatar en la barra lateral, admite recursos locales o CORS
avatar:

# La URL de la imagen de vista previa social utilizada en la metaetiqueta `og:image` de SEO.
# Puede ser sobrescrito por una `page.image` personalizada en el front matter.
social_preview_image: # cadena, recursos locales o CORS

# tipo booleano, interruptor global para TOC en publicaciones.
toc: true

comments:
  # Interruptor global para el sistema de comentarios en publicaciones. Mantener vacío significa desactivado.
  provider: # [disqus | utterances | giscus]
  # Las opciones del proveedor son las siguientes:
  disqus:
    shortname: # completa con el nombre corto de Disqus. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # Configuración de utterances › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Opciones de Giscus › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # opcional, por defecto 'pathname'
    strict: # opcional, por defecto '0'
    input_position: # opcional, por defecto 'bottom'
    lang: # opcional, por defecto al valor de `site.lang`
    reactions_enabled: # opcional, por defecto al valor de `1`

# Activos estáticos auto-alojados, opcional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # booleano, mantener vacío significa falso
    # especifica el entorno de Jekyll, vacío significa ambos
    # solo funciona si `assets.self_host.enabled` es 'true'
    env: # [development | production]

pwa:
  enabled: true # La opción para la característica PWA (instalable)
  cache:
    enabled: true # La opción para la caché offline de PWA
    # Las rutas definidas aquí serán excluidas de la caché PWA.
    # Generalmente su valor es el `baseurl` de otro sitio web que
    # comparte el mismo nombre de dominio que el sitio web actual.
    deny_paths:
      # - "/example"  # Las URLs que coincidan con `<SITE_URL>/example/*` no serán cacheadas por el PWA

paginate: 10

# La URL base de tu sitio
baseurl: ""

# ------------ Las siguientes opciones no se recomienda modificar ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Opciones de Rouge › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # Una cadena vacía aquí significa todos los archivos en el proyecto
      type: posts
    values:
      layout: post
      comments: true # Habilitar comentarios en publicaciones.
      toc: true # Mostrar columna de TOC en publicaciones.
      # NO modifiques el siguiente parámetro a menos que tengas suficiente confianza
      # para actualizar el código de todos los enlaces de publicaciones en este proyecto.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # ver `site.collections`
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - "*.config.js"
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

